export const ICON: { [key: string]: string } = {
  default: '',
  download: 'icon-download',
  delete: 'icon-delete',
  upload: 'icon-upload',
  search: 'icon-search',
  archive: 'icon-archive',
  save: 'icon-save',
  edit: 'icon-edit',
  add: 'icon-add',
  print: 'icon-print',
  more: 'icon-more',
  cancel: 'icon-cancel',
  close: 'icon-close',
  file: 'icon-file',
  clone: 'icon-clone',
  bell: 'icon-bell',
  send: 'icon-send',
  write: 'icon-write',
  accept: 'icon-accept',
  tag: 'icon-tag',
  home: 'icon-home',
  logout: 'icon-logout',
  update: 'icon-update',
  leftArrow: 'icon-left-arrow',
  rightArrow: 'icon-right-arrow',
  upArrow: 'icon-up-arrow',
  downArrow: 'icon-down-arrow',
  alignLeft: 'icon-align-left',
  tiInfoAlt: 'ti-info-alt',
  tiStamp: 'ti-stamp',
  tiPencilAlt: 'ti-pencil-alt'
};

export const ICO: { [key: string]: string } = {
  write: 'ico-write',
  files: 'ico-files',
  user: 'ico-user',
  bag: 'ico-bag',
  package: 'ico-package',
  bookmark: 'ico-bookmark-alt',
  wallet: 'ico-wallet',
  briefcase: 'ico-briefcase'
};
