// import { genderOptions } from "../../LegalEntity/LegalEntityPage";
import * as Yup from 'yup';
import {PrincipalULAdminTypes} from "../options/types";



const genderOptions = [
  { label: 'Мужской', value: 'male' },
  { label: 'Женский', value: 'female' },
 
];


export const AdminInulFields = [];

export const citizenshipOptions = [ //aystex nayi - mots valunere errora ttalis bayc valuunere chishten nshac
  { label: 'Афганистан', value: '004' },
  { label: 'Албания', value: '008' },
  { label: 'Антарктида', value: '010' },
  { label: 'Алжир', value: '012' },
  { label: 'Американское Самоа', value: '016' },
  { label: 'Андорра', value: '020' },
  { label: 'Ангола', value: '024' },
  { label: 'Антигуа и Барбуда', value: '028' },
  { label: 'Азербайджан', value: '031' },
  { label: 'Аргентина', value: '032' },
  { label: 'Австралия', value: '036' },
  { label: 'Австрия', value: '040' },
  { label: 'Багамы', value: '044' },
  { label: 'Бахрейн', value: '048' },
  { label: 'Бангладеш', value: '050' },
  { label: 'Армения', value: '051' },
  { label: 'Барбадос', value: '052' },
  { label: 'Бельгия', value: '056' },
  { label: 'Бермуды', value: '060' },
  { label: 'Бутан', value: '064' },
  { label: 'Боливия, Многонациональное Государство', value: '068' },
  { label: 'Босния и Герцеговина', value: '070' },
  { label: 'Ботсвана', value: '072' },
  { label: 'Остров Буве', value: '074' },
  { label: 'Бразилия', value: '076' },
  { label: 'Белиз', value: '084' },
  { label: 'Британская Территория в Индийском Океане', value: '086' },
  { label: 'Соломоновы Острова', value: '090' },
  { label: 'Виргинские Острова (Британские)', value: '092' },
  { label: 'Бруней-Даруссалам', value: '096' },
  { label: 'Болгария', value: '100' },
  { label: 'Мьянма', value: '104' },
  { label: 'Бурунди', value: '108' },
  { label: 'Беларусь', value: '112' },
  { label: 'Камбоджа', value: '116' },
  { label: 'Камерун', value: '120' },
  { label: 'Канада', value: '124' },
  { label: 'Кабо-Верде', value: '132' },
  { label: 'Острова Кайман', value: '136' },
  { label: 'Центрально-Африканская Республика', value: '140' },
  { label: 'Шри-Ланка', value: '144' },
  { label: 'Чад', value: '148' },
  { label: 'Чили', value: '152' },
  { label: 'Китай', value: '156' },
  { label: 'Тайвань (Китай)', value: '158' },
  { label: 'Остров Рождества', value: '162' },
  { label: 'Кокосовые (Килинг) Острова', value: '166' },
  { label: 'Колумбия', value: '170' },
  { label: 'Коморы', value: '174' },
  { label: 'Майотта', value: '175' },
  { label: 'Конго', value: '178' },
  { label: 'Конго, Демократическая Республика', value: '180' },
  { label: 'Острова Кука', value: '184' },
  { label: 'Коста-Рика', value: '188' },
  { label: 'Хорватия', value: '191' },
  { label: 'Куба', value: '192' },
  { label: 'Кипр', value: '196' },
  { label: 'Чехия', value: '203' },
  { label: 'Бенин', value: '204' },
  { label: 'Дания', value: '208' },
  { label: 'Доминика', value: '212' },
  { label: 'Доминиканская Республика', value: '214' },
  { label: 'Эквадор', value: '218' },
  { label: 'Эль-Сальвадор', value: '222' },
  { label: 'Экваториальная Гвинея', value: '226' },
  { label: 'Эфиопия', value: '231' },
  { label: 'Эритрея', value: '232' },
  { label: 'Эстония', value: '233' },
  { label: 'Фарерские Острова', value: '234' },
  { label: 'Фолклендские Острова (Мальвинские)', value: '238' },
  { label: 'Южная Джорджия и Южные Сандвичевы Острова', value: '239' },
  { label: 'Фиджи', value: '242' },
  { label: 'Финляндия', value: '246' },
  { label: 'Аландские Острова', value: '248' },
  { label: 'Франция', value: '250' },
  { label: 'Французская Гвиана', value: '254' },
  { label: 'Французская Полинезия', value: '258' },
  { label: 'Французские Южные Территории', value: '260' },
  { label: 'Джибути', value: '262' },
  { label: 'Габон', value: '266' },
  { label: 'Грузия', value: '268' },
  { label: 'Гамбия', value: '270' },
  { label: 'Палестина, Государство', value: '275' },
  { label: 'Германия', value: '276' },
  { label: 'Гана', value: '288' },
  { label: 'Гибралтар', value: '292' },
  { label: 'Кирибати', value: '296' },
  { label: 'Греция', value: '300' },
  { label: 'Гренландия', value: '304' },
  { label: 'Гренада', value: '308' },
  { label: 'Гваделупа', value: '312' },
  { label: 'Гуам', value: '316' },
  { label: 'Гватемала', value: '320' },
  { label: 'Гвинея', value: '324' },
  { label: 'Гайана', value: '328' },
  { label: 'Гаити', value: '332' },
  { label: 'Остров Херд и Острова Макдональд', value: '334' },
  { label: 'Папский Престол (Государство - Город Ватикан)', value: '336' },
  { label: 'Гондурас', value: '340' },
  { label: 'Гонконг', value: '344' },
  { label: 'Венгрия', value: '348' },
  { label: 'Исландия', value: '352' },
  { label: 'Индия', value: '356' },
  { label: 'Индонезия', value: '360' },
  { label: 'Иран (Исламская Республика)', value: '364' },
  { label: 'Ирак', value: '368' },
  { label: 'Ирландия', value: '372' },
  { label: 'Израиль', value: '376' },
  { label: 'Италия', value: '380' },
  { label: 'Кот Д\'Ивуар', value: '384' },
  { label: 'Ямайка', value: '388' },
  { label: 'Япония', value: '392' },
  { label: 'Казахстан', value: '398' },
  { label: 'Иордания', value: '400' },
  { label: 'Кения', value: '404' },
  { label: 'Корея, Народно-Демократическая Республика', value: '408' },
  { label: 'Корея, Республика', value: '410' },
  { label: 'Кувейт', value: '414' },
  { label: 'Киргизия', value: '417' },
  { label: 'Лаосская Народно-Демократическая Республика', value: '418' },
  { label: 'Ливан', value: '422' },
  { label: 'Лесото', value: '426' },
  { label: 'Латвия', value: '428' },
  { label: 'Либерия', value: '430' },
  { label: 'Ливия', value: '434' },
  { label: 'Лихтенштейн', value: '438' },
  { label: 'Литва', value: '440' },
  { label: 'Люксембург', value: '442' },
  { label: 'Макао', value: '446' },
  { label: 'Мадагаскар', value: '450' },
  { label: 'Малави', value: '454' },
  { label: 'Малайзия', value: '458' },
  { label: 'Мальдивы', value: '462' },
  { label: 'Мали', value: '466' },
  { label: 'Мальта', value: '470' },
  { label: 'Мартиника', value: '474' },
  { label: 'Мавритания', value: '478' },
  { label: 'Маврикий', value: '480' },
  { label: 'Мексика', value: '484' },
  { label: 'Монако', value: '492' },
  { label: 'Монголия', value: '496' },
  { label: 'Молдова, Республика', value: '498' },
  { label: 'Черногория', value: '499' },
  { label: 'Монтсеррат', value: '500' },
  { label: 'Марокко', value: '504' },
  { label: 'Мозамбик', value: '508' },
  { label: 'Оман', value: '512' },
  { label: 'Намибия', value: '516' },
  { label: 'Науру', value: '520' },
  { label: 'Непал', value: '524' },
  { label: 'Нидерланды, Королевство', value: '528' },
  { label: 'Кюрасао', value: '531' },
  { label: 'Аруба', value: '533' },
  { label: 'Сен-Мартен (нидерландская часть)', value: '534' },
  { label: 'Бонэйр, Синт-Эстатиус и Саба', value: '535' },
  { label: 'Новая Каледония', value: '540' },
  { label: 'Вануату', value: '548' },
  { label: 'Новая Зеландия', value: '554' },
  { label: 'Никарагуа', value: '558' },
  { label: 'Нигер', value: '562' },
  { label: 'Нигерия', value: '566' },
  { label: 'Ниуэ', value: '570' },
  { label: 'Остров Норфолк', value: '574' },
  { label: 'Норвегия', value: '578' },
  { label: 'Северные Марианские Острова', value: '580' },
  { label: 'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов', value: '581' },
  { label: 'Микронезия, Федеративные Штаты', value: '583' },
  { label: 'Маршалловы Острова', value: '584' },
  { label: 'Палау', value: '585' },
  { label: 'Пакистан', value: '586' },
  { label: 'Панама', value: '591' },
  { label: 'Папуа-Новая Гвинея', value: '598' },
  { label: 'Парагвай', value: '600' },
  { label: 'Перу', value: '604' },
  { label: 'Филиппины', value: '608' },
  { label: 'Питкэрн', value: '612' },
  { label: 'Польша', value: '616' },
  { label: 'Португалия', value: '620' },
  { label: 'Гвинея-Бисау', value: '624' },
  { label: 'Тимор-Лесте', value: '626' },
  { label: 'Пуэрто-Рико', value: '630' },
  { label: 'Катар', value: '634' },
  { label: 'Реюньон', value: '638' },
  { label: 'Румыния', value: '642' },
  { label: 'Россия', value: '643' },
  { label: 'Руанда', value: '646' },
  { label: 'Сен-Бартелеми', value: '652' },
  { label: 'Святая Елена, Остров Вознесения, Тристан-да-Кунья', value: '654' },
  { label: 'Сент-Китс и Невис', value: '659' },
  { label: 'Ангилья', value: '660' },
  { label: 'Сент-Люсия', value: '662' },
  { label: 'Сен-Мартен (французская часть)', value: '663' },
  { label: 'Сен-Пьер и Микелон', value: '666' },
  { label: 'Сент-Винсент и Гренадины', value: '670' },
  { label: 'Сан-Марино', value: '674' },
  { label: 'Сан-Томе и Принсипи', value: '678' },
  { label: 'Саудовская Аравия', value: '682' },
  { label: 'Сенегал', value: '686' },
  { label: 'Сербия', value: '688' },
  { label: 'Сейшелы', value: '690' },
  { label: 'Сьерра-Леоне', value: '694' },
  { label: 'Сингапур', value: '702' },
  { label: 'Словакия', value: '703' },
  { label: 'Вьетнам', value: '704' },
  { label: 'Словения', value: '705' },
  { label: 'Сомали', value: '706' },
  { label: 'Южная Африка', value: '710' },
  { label: 'Зимбабве', value: '716' },
  { label: 'Испания', value: '724' },
  { label: 'Южный Судан', value: '728' },
  { label: 'Судан', value: '729' },
  { label: 'Западная Сахара', value: '732' },
  { label: 'Суринам', value: '740' },
  { label: 'Шпицберген и Ян Майен', value: '744' },
  { label: 'Эсватини', value: '748' },
  { label: 'Швеция', value: '752' },
  { label: 'Швейцария', value: '756' },
  { label: 'Сирийская Арабская Республика', value: '760' },
  { label: 'Таджикистан', value: '762' },
  { label: 'Таиланд', value: '764' },
  { label: 'Того', value: '768' },
  { label: 'Токелау', value: '772' },
  { label: 'Тонга', value: '776' },
  { label: 'Тринидад и Тобаго', value: '780' },
  { label: 'Объединенные Арабские Эмираты', value: '784' },
  { label: 'Тунис', value: '788' },
  { label: 'Турция', value: '792' },
  { label: 'Туркмения', value: '795' },
  { label: 'Острова Теркс и Кайкос', value: '796' },
  { label: 'Тувалу', value: '798' },
  { label: 'Уганда', value: '800' },
  { label: 'Украина', value: '804' },
  { label: 'Северная Македония', value: '807' },
  { label: 'Египет', value: '818' },
  { label: 'Соединенное Королевство Великобритании и Северной Ирландии', value: '826' },
  { label: 'Гернси', value: '831' },
  { label: 'Джерси', value: '832' },
  { label: 'Остров Мэн', value: '833' },
  { label: 'Танзания, Объединенная Республика', value: '834' },
  { label: 'Соединенные Штаты', value: '840' },
  { label: 'Виргинские Острова (США)', value: '850' },
  { label: 'Буркина-Фасо', value: '854' },
  { label: 'Уругвай', value: '858' },
  { label: 'Узбекистан', value: '860' },
  { label: 'Венесуэла, Боливарианская Республика', value: '862' },
  { label: 'Уоллис и Футуна', value: '876' },
  { label: 'Самоа', value: '882' },
  { label: 'Йемен', value: '887' },
  { label: 'Замбия', value: '894' },
  { label: 'Абхазия', value: '895' },
  { label: 'Южная Осетия', value: '896' },
  { label: 'ДНР', value: '897' },
  { label: 'ЛНР', value: '898' }
];

export const nationalityOptions = [

  { label: 'Гражданин Российской Федерации', value: '1' },
  { label: 'Иностранный гражданин', value: '2' },
  { label: 'Лицо без гражданства', value: '3' },
];


export const documentCodeOptions = [  //aystex nayi - mots valunere errora ttalis bayc valuunere chishten nshac u ayystex chka value 22 - da chishta, der chka bayc paymannerum grvaca
  { label: 'Паспорт гражданина Российской Федерации', value: '21' },
  { label: 'Военный билет', value: '07' },
  { label: 'Паспорт иностранного гражданина', value: '10' },
  { label: 'Свидетельство о рассмотрении ходатайства о признании лица беженцем на территории Российской федерации по существу', value: '11' },
  { label: 'Вид на жительство в Российской Федерации', value: '12' },
  { label: 'Удостоверение беженца', value: '13' },
  { label: 'Разрешение на временное проживание в Российской Федерации', value: '15' },
  { label: 'Свидетельство о предоставлении временного убежища на территории Российской Федерации', value: '18' },
  { label: 'Удостоверение личности военнослужащего Российской Федерации', value: '24' },
];

export const ulAdminOptions = [
    { value: PrincipalULAdminTypes.IP, label: 'ИП' },
    { value: PrincipalULAdminTypes.UL, label: 'ЮЛ' },
    { value: PrincipalULAdminTypes.FL, label: 'ФЛ' },
  ];

export enum InULAdminTypes {
  FL = "SUBADMINFL"
}

export const inUlAdminOptions = [
    { value: InULAdminTypes.FL, label: 'ФЛ' },
  ];  
  
  const statusOptions = [
    { value: 'active', label: 'Active' },
    { value: 'revoked', label: 'Revoked' },
  ];
  const floorOptions = [
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
  ];
  
 export const AdminIPFields = [
  {section : 'Доверитель', fields : [
    { name: 'nameText', label: 'Наименование', type: 'input', required: false, placeholder:'Введите наименование ИП' , title:'Введите строку длиной 1-1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков') },
    { name: 'ogrn', label: 'ОГРНИП*', type: 'input', required: true,  placeholder:'Введите ОГРНИП' , title:'Введите 15-значный код' , validation: Yup.string().length(15, 'Введите номер длиной 15 знаков').required('Введите 15-значный код')},
    { name: 'inn', label: 'ИНН*', type: 'input', required: true, placeholder:'Введите ИНН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков').required('Введите 12-значный код')},
    { name: 'socialNumber', label: 'СНИЛС*', type: 'input', required: true, placeholder:'Введите СНИЛС' , title:'Введите 14-значный код' , validation: Yup.string().length(14,'Введите число длиной 14 знаков').required('Введите 14-значный код')},
    { name: 'surname', label: 'Фамилия*', type: 'input', required: true , placeholder:'Введите Фамилию' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков').required('Поле обязательно для ввода')},
    { name: 'name', label: 'Имя*', type: 'input', required: true , placeholder:'Введите Имя' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков').required('Поле обязательно для ввода')},
    { name: 'patronymic', label: 'Отчество', type: 'input', required: false , placeholder:'Введите Отчество' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков')},,
    { name: 'gender', label: 'Пол', type: 'select', options: genderOptions, required: false },  //ira mot male female tarberaknerrnen
    { name: 'citizenshipMark', label: 'Наличие гражданства', type: 'select', options: nationalityOptions, required: false }, // ira mot russian, foreign, none
    { name: 'ernNumber', label: 'Номер ЕРН', type: 'input', required: false , placeholder:'Введите номер ЕРН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков')},
    { name: 'birthday', label: 'Дата рождения', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
    { name: 'birthPlace', label: 'Место рождения', type: 'input', required: false , placeholder:'Введите место рождения' , title:'Введите строку длиной до 250 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-250 знаков').max(250, 'Введите строку длиной 1-250 знаков')},
    { name: 'citizenship', label: 'Гражданство', type: 'select' ,options: citizenshipOptions , required: false },
  ]},
  {id:'address' , section : 'Сведения об адресе жительства', fields : [
    { name: 'regionCode', label: 'Код региона', type: 'input', required: false , placeholder:'Введите код региона' , title:'Введите строку длиной 2 знака', validation: Yup.string().length(2,'Введите строку длиной 2 знака')},
    { name: 'Index', label: 'Индекс', type: 'input', required: false , placeholder:'Введите индекс' , title:'Введите строку длиной 6 знаков', validaion: Yup.string().length(6,'Введите строку длиной 6 знаков')},
    { name: 'Province', label: 'Район', type: 'input', required: false ,placeholder:'Введите название района' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'city', label: 'Город', type: 'input', required: false ,placeholder:'Введите город' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'settlement', label: 'Населенный пункт', type: 'input', required: false ,placeholder:'Введите название населенного пункта' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'street', label: 'Улица', type: 'input', required: false ,placeholder:'Введите улицу' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'house', label: 'Дом', type: 'input', required: false ,placeholder:'Введите номер дома' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'block', label: 'Корпус', type: 'input', required: false ,placeholder:'Введите корпус' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'flat', label: 'Офис/квартира', type: 'input', required: false ,placeholder:'Введите номер офиса или квартиры' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
    { name: 'fiasId', label: 'Идентификатор адреса ФИАС', type: 'input', required: false , placeholder:'Введиите идентификатор адреса ФИАС' , title:'Введите число длиной 36 знаков' , validation: Yup.string().length(36,'Введите число длиной 36 знаков')},
    { name: 'fiasText', label: 'ФИАС адрес в РФ', type: 'input', required: false , placeholder:'Введиите ФИАС адрес' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')}, 
  ]},
  {section : 'Контактные данные', fields : [
    { name: 'phone', label: 'Номер контактного телефона/факс', type: 'input', required: false ,placeholder:'Введите телефон' , title:'Введите строку длиной 1-50 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков')}, 
    { name: 'email', label: 'Email', type: 'input', required: false ,placeholder:'Введите email' , title:'Введите строку длиной 3-129 знаков' , validation: Yup.string().email('Invalid email').min(3,'Введите строку длиной 3-129 знаков').max(129,'Введите строку длиной 3-129 знаков')}, 
  ]},
  {section : 'Документ подтверждающий полномочия лица', fields : [
    { name: 'documentName', label: 'Наименование документа', type: 'input', required: false ,placeholder:'Введите наименование документа' , title:'Введите строку длиной 1-120 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-120 знаков').max(120, 'Введите строку длиной 1-120 знаков')},
    { name: 'issuedAtDocument', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
    { name: 'issuedByDocument', label: 'Наименование органа выдавшего документ', type: 'input', required: false ,placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
    { name: 'certification', label: 'Сведения об удостоверении документа', type: 'input', required: false ,placeholder:'Введите cведения об удостоверении документа' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
  ]},
  {section : 'Документ удостоверяющий личность', fields : [
    { name: 'kind', label: 'Код вида документа', type: 'select' , options:documentCodeOptions , required: false }, 
    { name: 'serialnumber', label: 'Серия и номер документа', type: 'input', required: false  ,placeholder:'Введите серию и номер документа' , title:'Введите строку длиной 1-25 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-25 знаков').max(25, 'Введите строку длиной 1-25 знаков')},
    { name: 'issuedAt', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата' },
    { name: 'issuer', label: 'Наименование органа, выдавшего документ', type: 'input', required: false , placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 4000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-4000 знаков').max(4000, 'Введите строку длиной 1-4000 знаков')},
    { name: 'issuerCode', label: 'Код подразделения органа, выдавшего документ', type: 'input', required: false ,placeholder:'Введите код подразделения органа, выдавшего документ' , title:'Введите строку длиной 7 знаков' , validation:Yup.string().length(7,'Введите строку длиной 7 знаков')},
    { name: 'expireAt', label: 'Дата истечения срока действия документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата' },
  ]},
  ];
 export const AdminFlFields = [
    {section : 'Доверитель', fields : [
      { name: 'socialNumber', label: 'СНИЛС*', type: 'input', required: true, placeholder:'Введите СНИЛС' , title:'Введите 14-значный код' , validation: Yup.string().length(14,'Введите число длиной 14 знаков').required('Поле обязательно для ввода')},
      { name: 'inn', label: 'ИНН', type: 'input', required: false, placeholder:'Введите ИНН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков')},
      { name: 'surname', label: 'Фамилия*', type: 'input', required: true , placeholder:'Введите Фамилию' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков').required('Поле обязательно для ввода')},
      { name: 'nameText', label: 'Имя*', type: 'input', required: true , placeholder:'Введите Имя' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков')},
      { name: 'patronymic', label: 'Отчество', type: 'input', required: false , placeholder:'Введите Отчество' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков')},,
      { name: 'position', label: 'Должность', type: 'input', required: false  ,placeholder:'Введите должность' , title:'Введите строку длиной до 255 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-255 знаков').max(255, 'Введите строку длиной 1-255 знаков')},
      { name: 'gender', label: 'Пол', type: 'select', options: genderOptions, required: false },  //ira mot male female tarberaknerrnen
      { name: 'citizenshipMark', label: 'Наличие гражданства', type: 'select', options: nationalityOptions, required: false }, // ira mot russian, foreign, none
      { name: 'ernNumber', label: 'Номер ЕРН', type: 'input', required: false , placeholder:'Введите номер ЕРН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков')},
      { name: 'birthday', label: 'Дата рождения', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
      { name: 'birthPlace', label: 'Место рождения', type: 'input', required: false , placeholder:'Введите место рождения' , title:'Введите строку длиной до 250 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-250 знаков').max(250, 'Введите строку длиной 1-250 знаков')},
      { name: 'citizenship', label: 'Гражданство', type: 'select' ,options: citizenshipOptions , required: false },
    ]},
    {id:'address' , section : 'Сведения об адресе жительства', fields : [
      { name: 'regionCode', label: 'Код региона', type: 'input', required: false , placeholder:'Введите код региона' , title:'Введите строку длиной 2 знака', validation: Yup.string().length(2,'Введите строку длиной 2 знака')},
      { name: 'Index', label: 'Индекс', type: 'input', required: false , placeholder:'Введите индекс' , title:'Введите строку длиной 6 знаков', validaion: Yup.string().length(6,'Введите строку длиной 6 знаков')},
      { name: 'Province', label: 'Район', type: 'input', required: false ,placeholder:'Введите название района' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'city', label: 'Город', type: 'input', required: false ,placeholder:'Введите город' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'settlement', label: 'Населенный пункт', type: 'input', required: false ,placeholder:'Введите название населенного пункта' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'street', label: 'Улица', type: 'input', required: false ,placeholder:'Введите улицу' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'house', label: 'Дом', type: 'input', required: false ,placeholder:'Введите номер дома' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'block', label: 'Корпус', type: 'input', required: false ,placeholder:'Введите корпус' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'flat', label: 'Офис/квартира', type: 'input', required: false ,placeholder:'Введите номер офиса или квартиры' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'fiasId', label: 'Идентификатор адреса ФИАС', type: 'input', required: false , placeholder:'Введиите идентификатор адреса ФИАС' , title:'Введите число длиной 36 знаков' , validation: Yup.string().length(36,'Введите число длиной 36 знаков')},
      { name: 'fiasText', label: 'ФИАС адрес в РФ', type: 'input', required: false , placeholder:'Введиите ФИАС адрес' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')}, 
    ]},
    {section : 'Контактные данные', fields : [
      { name: 'phone', label: 'Номер контактного телефона/факс', type: 'input', required: false ,placeholder:'Введите телефон' , title:'Введите строку длиной 1-50 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков')}, 
      { name: 'email', label: 'Email', type: 'input', required: false ,placeholder:'Введите email' , title:'Введите строку длиной 3-129 знаков' , validation: Yup.string().email('Invalid email').min(3,'Введите строку длиной 3-129 знаков').max(129,'Введите строку длиной 3-129 знаков')}, 
    ]},
    {section : 'Документ подтверждающий полномочия лица', fields : [
      { name: 'documentName', label: 'Наименование документа', type: 'input', required: false ,placeholder:'Введите наименование документа' , title:'Введите строку длиной 1-120 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-120 знаков').max(120, 'Введите строку длиной 1-120 знаков')},
      { name: 'issuedAtDocument', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
      { name: 'issuedByDocument', label: 'Наименование органа выдавшего документ', type: 'input', required: false ,placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
      { name: 'certification', label: 'Сведения об удостоверении документа', type: 'input', required: false ,placeholder:'Введите cведения об удостоверении документа' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
    ]},
    {section : 'Документ удостоверяющий личность', fields : [
      { name: 'kind', label: 'Код вида документа', type: 'select' , options:documentCodeOptions , required: false }, 
      { name: 'serialnumber', label: 'Серия и номер документа', type: 'input', required: false  ,placeholder:'Введите серию и номер документа' , title:'Введите строку длиной 1-25 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-25 знаков').max(25, 'Введите строку длиной 1-25 знаков')},
      { name: 'issuedAt', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата' },
      { name: 'issuer', label: 'Наименование органа, выдавшего документ', type: 'input', required: false , placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 4000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-4000 знаков').max(4000, 'Введите строку длиной 1-4000 знаков')},
      { name: 'issuerCode', label: 'Код подразделения органа, выдавшего документ', type: 'input', required: false ,placeholder:'Введите код подразделения органа, выдавшего документ' , title:'Введите строку длиной 7 знаков' , validation:Yup.string().length(7,'Введите строку длиной 7 знаков')},
      { name: 'expireAt', label: 'Дата истечения срока действия документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата' },
    ]},
  ];


// TODO all address section required by default
  export const AdminUlFields = [
    {section : 'Доверитель', fields : [
      { name: 'nameText', label: 'Наименование компании*', type: 'input', required: true, placeholder:'Введите наименование компании' , title:'Введите строку длиной 1-1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000,'Введите строку длиной 1-1000 знаков').required('Поле обязательно для ввода')},
      { name: 'inn', label: 'ИНН*', type: 'input', required: true, placeholder:'Введите ИНН' , title:'Введите 10-значный код' , validation: Yup.string().length(10,'Введите число длиной 10 знаков').required('Введите 10-значный код')},
      { name: 'kpp', label: 'КПП*', type: 'input', required: true, placeholder:'Введите КПП' , title:'Введите 9-значный Код Причины Постановки на учет' , validation: Yup.string().length(9,'Введите код длиной 9 знаков').required('Введите 9-значный Код Причины Постановки на учет')},
      { name: 'ogrn', label: 'ОГРН*', type: 'input', required: true,  placeholder:'Введите ОГРН' , title:'Введите 13-значный код' , validation: Yup.string().length(13, 'Введите код длиной 13 знаков').required('Введите 13-значный код')},
      { name: 'constituentDoc', label: 'Наименование учредительного документа', type: 'input', required: false, placeholder:'Введите наименование учредительного документа' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков') },
    ]},
    {id:'address' , section : 'Сведения об адресе', fields : [
      { name: 'regionCode', label: 'Код региона*', type: 'input', required: false , placeholder:'Введите код региона' , title:'Введите строку длиной 2 знака', validation: Yup.string().length(2,'Введите строку длиной 2 знака')},
      { name: 'Index', label: 'Индекс*', type: 'input', required: false , placeholder:'Введите индекс' , title:'Введите строку длиной 6 знаков', validaion: Yup.string().length(6,'Введите строку длиной 6 знаков')},
      { name: 'Province', label: 'Район', type: 'input', required: false ,placeholder:'Введите название района' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'city', label: 'Город*', type: 'input', required: false ,placeholder:'Введите город' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'settlement', label: 'Населенный пункт', type: 'input', required: false ,placeholder:'Введите название населенного пункта' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'street', label: 'Улица*', type: 'input', required: false ,placeholder:'Введите улицу' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'house', label: 'Дом*', type: 'input', required: false ,placeholder:'Введите номер дома' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'block', label: 'Корпус', type: 'input', required: false ,placeholder:'Введите корпус' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'flat', label: 'Офис/квартира*', type: 'input', required: false ,placeholder:'Введите номер офиса или квартиры' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'fiasId', label: 'Идентификатор адреса ФИАС*', type: 'input', required: false , placeholder:'Введиите идентификатор адреса ФИАС' , title:'Введите число длиной 36 знаков' , validation: Yup.string().length(36,'Введите число длиной 36 знаков')},
      { name: 'fiasText', label: 'ФИАС адрес в РФ*', type: 'input', required: false , placeholder:'Введиите ФИАС адрес' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')}, 
    ]},
    {section : 'Контактные данные', fields : [
      { name: 'phone', label: 'Номер контактного телефона/факс', type: 'input', required: false ,placeholder:'Введите телефон' , title:'Введите строку длиной 1-50 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков')}, 
      { name: 'email', label: 'Email', type: 'input', required: false ,placeholder:'Введите email' , title:'Введите строку длиной 3-129 знаков' , validation: Yup.string().email('Invalid email').min(3,'Введите строку длиной 3-129 знаков').max(129,'Введите строку длиной 3-129 знаков')}, 
    ]},
    {section : 'Документ подтверждающий полномочия лица', fields : [
      { name: 'documentName', label: 'Наименование документа', type: 'input', required: false ,placeholder:'Введите наименование документа' , title:'Введите строку длиной 1-120 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-120 знаков').max(120, 'Введите строку длиной 1-120 знаков')},
      { name: 'issuedAtDocument', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
      { name: 'issuedByDocument', label: 'Наименование органа выдавшего документ', type: 'input', required: false ,placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
      { name: 'certification', label: 'Сведения об удостоверении документа', type: 'input', required: false ,placeholder:'Введите cведения об удостоверении документа' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
    ]},
    {section : 'Admin', fields : [
      { name: 'Admin', label: 'Phone', type: 'button', required: false }, 
      
    ]},
  ];
  

  export const AdminInulFLFields = [
    {section : 'Доверитель', fields : [
      { name: 'socialNumber', label: 'СНИЛС', type: 'input', required: false, placeholder:'Введите СНИЛС' , title:'Введите 14-значный код' , validation: Yup.string().length(14,'Введите число длиной 14 знаков')},
      { name: 'inn', label: 'ИНН', type: 'input', required: false, placeholder:'Введите ИНН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков')},
      { name: 'surname', label: 'Фамилия*', type: 'input', required: true , placeholder:'Введите Фамилию' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков').required('Поле обязательно для ввода')},
      { name: 'nameText', label: 'Имя*', type: 'input', required: true , placeholder:'Введите Имя' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков').required('Поле обязательно для ввода')},
      { name: 'patronymic', label: 'Отчество', type: 'input', required: false , placeholder:'Введите Отчество' , title:'Введите строку длиной до 200 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-200 знаков').max(200, 'Введите строку длиной 1-200 знаков')},,
      { name: 'position', label: 'Должность', type: 'input', required: false  ,placeholder:'Введите должность' , title:'Введите строку длиной до 255 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-255 знаков').max(255, 'Введите строку длиной 1-255 знаков')},
      { name: 'gender', label: 'Пол', type: 'select', options: genderOptions, required: false },  //ira mot male female tarberaknerrnen
      { name: 'citizenshipMark', label: 'Наличие гражданства', type: 'select', options: nationalityOptions, required: false }, // ira mot russian, foreign, none
      { name: 'ernNumber', label: 'Номер ЕРН', type: 'input', required: false , placeholder:'Введите номер ЕРН' , title:'Введите 12-значный код' , validation: Yup.string().length(12,'Введите число длиной 12 знаков')},
      { name: 'birthday', label: 'Дата рождения', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
      { name: 'birthPlace', label: 'Место рождения', type: 'input', required: false , placeholder:'Введите место рождения' , title:'Введите строку длиной до 250 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-250 знаков').max(250, 'Введите строку длиной 1-250 знаков')},
      { name: 'citizenship', label: 'Гражданство', type: 'select' ,options: citizenshipOptions , required: false },
    ]},
    {id:'address' , section : 'Сведения об адресе жительства', fields : [
      { name: 'regionCode', label: 'Код региона', type: 'input', required: false , placeholder:'Введите код региона' , title:'Введите строку длиной 2 знака', validation: Yup.string().length(2,'Введите строку длиной 2 знака')},
      { name: 'Index', label: 'Индекс', type: 'input', required: false , placeholder:'Введите индекс' , title:'Введите строку длиной 6 знаков', validaion: Yup.string().length(6,'Введите строку длиной 6 знаков')},
      { name: 'Province', label: 'Район', type: 'input', required: false ,placeholder:'Введите название района' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'city', label: 'Город', type: 'input', required: false ,placeholder:'Введите город' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'settlement', label: 'Населенный пункт', type: 'input', required: false ,placeholder:'Введите название населенного пункта' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'street', label: 'Улица', type: 'input', required: false ,placeholder:'Введите улицу' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'house', label: 'Дом', type: 'input', required: false ,placeholder:'Введите номер дома' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'block', label: 'Корпус', type: 'input', required: false ,placeholder:'Введите корпус' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'flat', label: 'Офис/квартира', type: 'input', required: false ,placeholder:'Введите номер офиса или квартиры' , title:'Введите строку длиной до 50 знаков' , validaion: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков') },
      { name: 'fiasId', label: 'Идентификатор адреса ФИАС', type: 'input', required: false , placeholder:'Введиите идентификатор адреса ФИАС' , title:'Введите число длиной 36 знаков' , validation: Yup.string().length(36,'Введите число длиной 36 знаков')},
      { name: 'fiasText', label: 'ФИАС адрес в РФ', type: 'input', required: false , placeholder:'Введиите ФИАС адрес' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')}, 
    ]},
    {section : 'Контактные данные', fields : [
      { name: 'phone', label: 'Номер контактного телефона/факс', type: 'input', required: false ,placeholder:'Введите телефон' , title:'Введите строку длиной 1-50 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-50 знаков').max(50, 'Введите строку длиной 1-50 знаков')}, 
      { name: 'email', label: 'Email', type: 'input', required: false ,placeholder:'Введите email' , title:'Введите строку длиной 3-129 знаков' , validation: Yup.string().email('Invalid email').min(3,'Введите строку длиной 3-129 знаков').max(129,'Введите строку длиной 3-129 знаков')}, 
    ]},
    {section : 'Документ подтверждающий полномочия лица', fields : [
      { name: 'documentName', label: 'Наименование документа', type: 'input', required: false ,placeholder:'Введите наименование документа' , title:'Введите строку длиной 1-120 знаков', validation: Yup.string().min(1, 'Введите строку длиной 1-120 знаков').max(120, 'Введите строку длиной 1-120 знаков')},
      { name: 'issuedAtDocument', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата'},
      { name: 'issuedByDocument', label: 'Наименование органа выдавшего документ', type: 'input', required: false ,placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
      { name: 'certification', label: 'Сведения об удостоверении документа', type: 'input', required: false ,placeholder:'Введите cведения об удостоверении документа' , title:'Введите строку длиной до 1000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-1000 знаков').max(1000, 'Введите строку длиной 1-1000 знаков')},
    ]},
    {section : 'Документ удостоверяющий личность', fields : [
      { name: 'kind', label: 'Код вида документа', type: 'select' , options:documentCodeOptions , required: false }, 
      { name: 'serialnumber', label: 'Серия и номер документа', type: 'input', required: false  ,placeholder:'Введите серию и номер документа' , title:'Введите строку длиной 1-25 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-25 знаков').max(25, 'Введите строку длиной 1-25 знаков')},
      { name: 'issuedAt', label: 'Дата выдачи документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy' , placeholder:'Дата'},
      { name: 'issuer', label: 'Наименование органа, выдавшего документ', type: 'input', required: false , placeholder:'Введите наименование органа, выдавшего документ' , title:'Введите строку длиной до 4000 знаков' , validation: Yup.string().min(1, 'Введите строку длиной 1-4000 знаков').max(4000, 'Введите строку длиной 1-4000 знаков')},
      { name: 'issuerCode', label: 'Код подразделения органа, выдавшего документ', type: 'input', required: false ,placeholder:'Введите код подразделения органа, выдавшего документ' , title:'Введите строку длиной 7 знаков' , validation:Yup.string().length(7,'Введите строку длиной 7 знаков')},
      { name: 'expireAt', label: 'Дата истечения срока действия документа', type: 'date', required: false, title:'Введите дату в формате dd.mm.yyyy', placeholder:'Дата' },
    ]},
  ];