export const doveritel = {
    "nameText": "ООО «Рога и Копыта»",
    "email": "baboomian53@gmail.com",
    "Index": "11",
    "phone": "077041898",
    "province": "Yerevan",
    "regionCode": "Yerevan",
    "inn": "1111111111",
    "kpp": "781001001",
    "legalDoc": "sss",
    "ogrn": "1111111111111",
    "status": "active",
    "type": "UL",
    "citizenship": "",
    "fiasAddressId": "gulbenyan 43",
    "documentTypeCode": "dsd",
    "issuingAuthorityCode": "sdsd",
    "placeOfBirth": "dsdd",
    "issuingAuthorityName": "sdsd",
    "citizenshipStatus": "active",
    "ernNumber": "dsd",
    "patronymic": "ddd",
    "gender": "male",
    "documentSeriesNumber": "sdsd",
    "fiasAddressInRF": "gulbenyan 43",
    "city": "Yerevan",
    "house": "43",
    "firstName": "Arno",
    "apartment": "sdsds",
    "building": "dsds",
    "locality": "Yerevan",
    "street": "Gulbenyan",
    "lastName": "Baboomian"
  }
export const representative = {
    "email": "baboomian53@gmail.com",
    "index": "sd",
    "phone": "077041898",
    "province": "Yerevan",
    "regionCode": "Yerevan",
    "inn": "dadaddadaa",
    "kpp": "781001001",
    "legalDoc": "sss",
    "ogrn": "dsssaaaaaaaaa",
    "status": "active",
    "type": "IP",
    "citizenship": "dsdsd",
    "fiasAddressId": "gulbenyan 43",
    "documentTypeCode": "dsd",
    "issuingAuthorityCode": "sdsd",
    "placeOfBirth": "dsdd",
    "issuingAuthorityName": "sdsd",
    "citizenshipStatus": "active",
    "ernNumber": "11",
    "patronymic": "ddd",
    "gender": "male",
    "documentSeriesNumber": "sdsd",
    "fiasAddressInRF": "gulbenyan 43",
    "city": "Yerevan",
    "house": "43",
    "firstName": "Arno",
    "apartment": "11",
    "building": "dsds",
    "locality": "Yerevan",
    "street": "Gulbenyan",
    "lastName": "Baboomian"
  }
  

 export const adminDetails = {
    email: "baboomian53@gmail.com",
    index: "11",
    phone: "077041898",
    province: "Yerevan",
    regionCode: "11",
    companyName: "baboomian inc.",
    inn: "Arno inc.",
    kpp: "781001001",
    type: "ИНЮЛ",
    legalAddressInRegistrationCountry: "gulbenyan 43",
    fiasAddressId: "43 Gulbenkian Street",
    taxpayerCodeInRegistrationCountry: "1111111",
    registeringAuthorityName: "111111",
    accreditationRecordNumber: "11111",
    registrationNumberInRegistrationCountry: "111111111",
    registrationCountry: "111111",
    fiasAddressInRF: "43 Gulbenkian Street",
    city: "Yerevan",
    building: "43",
    apartment: "11",
    block: "22",
    locality: "Yerevan",
    street: "Gulbenkian Street"
};
